DEBUG: false

DATASET:
  DATASET: 'dad'
  KEYPOINTS: 'gt_train'
  SUBJECTS_TRAIN: 'vp1,vp2,vp3,vp4,vp5,vp6,vp7,vp8,vp9,vp10'
  SUBJECTS_TEST: 'vp11,vp12'
  SUBJECTS_UNLABELED: ''
  ACTIONS: ''

MODEL:
  STRIDE: 1
  EPOCHS: 80
  BATCH_SIZE: 1024
  LR: 0.001
  DROPOUT: 0.25
  LR_DECAY: 0.98
  AUGMENTATION: true
  TEST_TIME_AUGMENTATION: true
  ARCHITECTURE: 7,3,5
  CAUSAL: true
  CHANNELS: 1024
  
TRAIN:
  IS_TRAIN: true
  RESUME: ''
  EVALUATE: ''
  BY_SUBJECT: false
  NRUNS: 1

EXPS:
  BONE_SYM: false
  ILLEGAL_ANGLE: false
  LAMBDA_SYM: 1000.0
  LAMBDA_ANGLE: 0.001
  NO_PROJ: false
  SUBSET: 1.
  DOWNSAMPLE: 1
  WARMUP: 10
  LINEAR_PROJECTION: true
  BONE_LENGTH: true
  DISABLE_OPTIMIZATIONS: false
  EVAL: true
  DENSE: false

VIS:
  RENDER: false
  SUBJECT: ''
  ACTION: ''
  CAMERA: 0
  VIDEO: ''
  SKIP: 0
  OUTPUT: ''
  EXPORT: ''
  BITRATE: ''
  NO_GT: false
  FRAME_LIMIT: 200
  DOWNSAMPLE: 4
  SIZE: 6

LOGS:
  TENSORBOARD: ''
  EXPORT_TRAINING_CURVES: true
  CHECKPOINT: ''
  SAVE_CHECKPOINT: true
  CHECKPOINT_FREQUENCY: 100
  SEQ_START: 2000
  SEQ_LENGTH: 10000
  PAD: 2000

   